package gobithumb

type Currency string
type TimeInterval string
type SearchType string

const (
	AAVE  Currency = "aave"
	ADA   Currency = "ada"
	ADP   Currency = "adp"
	AION  Currency = "aion"
	ALGO  Currency = "algo"
	AMO   Currency = "amo"
	ANKR  Currency = "ankr"
	ANV   Currency = "anv"
	ANW   Currency = "anw"
	APIX  Currency = "apix"
	APM   Currency = "apm"
	ARPA  Currency = "arpa"
	ATOM  Currency = "atom"
	AWO   Currency = "awo"
	BAL   Currency = "bal"
	BASIC Currency = "basic"
	BAT   Currency = "bat"
	BCD   Currency = "bcd"
	BCH   Currency = "bch"
	BEL   Currency = "bel"
	BIOT  Currency = "biot"
	BLY   Currency = "bly"
	BOA   Currency = "boa"
	BORA  Currency = "bora"
	BSV   Currency = "bsv"
	BTC   Currency = "btc"
	BTG   Currency = "btg"
	BTT   Currency = "btt"
	CENNZ Currency = "cennz"
	CHR   Currency = "chr"
	COMP  Currency = "comp"
	CON   Currency = "con"
	COS   Currency = "cos"
	CRO   Currency = "cro"
	CTXC  Currency = "ctxc"
	DAD   Currency = "dad"
	DOT   Currency = "dot"
	EGG   Currency = "egg"
	EL    Currency = "el"
	ELF   Currency = "elf"
	ENJ   Currency = "enj"
	EOS   Currency = "eos"
	ETC   Currency = "etc"
	ETH   Currency = "eth"
	ETHOS Currency = "ethos"
	EVZ   Currency = "evz"
	FCT   Currency = "fct"
	FIT   Currency = "fit"
	FLETA Currency = "fleta"
	FX    Currency = "fx"
	GLM   Currency = "glm"
	GOM2  Currency = "gom2"
	GRT   Currency = "grt"
	GXC   Currency = "gxc"
	HIVE  Currency = "hive"
	ICX   Currency = "icx"
	IOST  Currency = "iost"
	IPX   Currency = "ipx"
	JST   Currency = "jst"
	KNC   Currency = "knc"
	LINK  Currency = "link"
	LOOM  Currency = "loom"
	LRC   Currency = "lrc"
	LTC   Currency = "ltc"
	LUNA  Currency = "luna"
	MBL   Currency = "mbl"
	META  Currency = "meta"
	MIR   Currency = "mir"
	MIX   Currency = "mix"
	MLK   Currency = "mlk"
	MTL   Currency = "mtl"
	MVC   Currency = "mvc"
	MXC   Currency = "mxc"
	OBSR  Currency = "obsr"
	OMG   Currency = "omg"
	ONG   Currency = "ong"
	ONT   Currency = "ont"
	ORBS  Currency = "orbs"
	ORC   Currency = "orc"
	POLA  Currency = "pola"
	POWR  Currency = "powr"
	QKC   Currency = "qkc"
	QTCON Currency = "qtcon"
	QTUM  Currency = "qtum"
	REN   Currency = "ren"
	REP   Currency = "rep"
	RINGX Currency = "ringx"
	SAND  Currency = "sand"
	SNT   Currency = "snt"
	SNX   Currency = "snx"
	SOC   Currency = "soc"
	SRM   Currency = "srm"
	SSX   Currency = "ssx"
	STEEM Currency = "steem"
	STRAX Currency = "strax"
	SUN   Currency = "sun"
	SXP   Currency = "sxp"
	TEMCO Currency = "temco"
	TFUEL Currency = "tfuel"
	THETA Currency = "theta"
	TMTG  Currency = "tmtg"
	TRUE  Currency = "true"
	TRV   Currency = "trv"
	TRX   Currency = "trx"
	UMA   Currency = "uma"
	UNI   Currency = "uni"
	VALOR Currency = "valor"
	VET   Currency = "vet"
	VSYS  Currency = "vsys"
	WAVES Currency = "waves"
	WAXP  Currency = "waxp"
	WEMIX Currency = "wemix"
	WICC  Currency = "wicc"
	WOM   Currency = "wom"
	WOZX  Currency = "wozx"
	WTC   Currency = "wtc"
	XEM   Currency = "xem"
	XLM   Currency = "xlm"
	XNO   Currency = "xno"
	XPR   Currency = "xpr"
	XRP   Currency = "xrp"
	XTZ   Currency = "xtz"
	YFI   Currency = "yfi"
	ZIL   Currency = "zil"
	ZRX   Currency = "zrx"

	KRW Currency = "krw"
	ALL Currency = "all" // -> 어떻게 짤 것인지 생각해봐야 함

	Min1   TimeInterval = "1m"
	Min3   TimeInterval = "3m"
	Min5   TimeInterval = "5m"
	Min10  TimeInterval = "10m"
	Min30  TimeInterval = "30m"
	Hour1  TimeInterval = "1h"
	Hour6  TimeInterval = "6h"
	Hour12 TimeInterval = "12h"
	Hour24 TimeInterval = "24h"

	All          SearchType = "0"
	BuyComplete  SearchType = "1"
	SellComplete SearchType = "2"
	InWidrawal   SearchType = "3"
	Deposit      SearchType = "4"
	Withdraw     SearchType = "5"
	InKRWDeposit SearchType = "9"
)

func COIN_ALL() []Currency {
	return []Currency{AAVE, ADA, ADP, AION, ALGO, AMO, ANKR, ANV, ANW, APIX, APM, ARPA, ATOM, AWO, BAL, BASIC, BAT, BCD, BCH, BEL, BIOT, BLY, BOA, BORA, BSV, BTC, BTG, BTT, CENNZ, CHR, COMP, CON, COS, CRO, CTXC, DAD, DOT, EGG, EL, ELF, ENJ, EOS, ETC, ETH, ETHOS, EVZ, FCT, FIT, FLETA, FX, GLM, GOM2, GRT, GXC, HIVE, ICX, IOST, IPX, JST, KNC, LINK, LOOM, LRC, LTC, LUNA, MBL, META, MIR, MIX, MLK, MTL, MVC, MXC, OBSR, OMG, ONG, ONT, ORBS, ORC, POLA, POWR, QKC, QTCON, QTUM, REN, REP, RINGX, SAND, SNT, SNX, SOC, SRM, SSX, STEEM, STRAX, SUN, SXP, TEMCO, TFUEL, THETA, TMTG, TRUE, TRV, TRX, UMA, UNI, VALOR, VET, VSYS, WAVES, WAXP, WEMIX, WICC, WOM, WOZX, WTC, XEM, XLM, XNO, XPR, XRP, XTZ, YFI, ZIL, ZRX}
}
